"""
Justification trace model — PRD 1.7

After an artwork is generated by the voting engine, build_trace produces a
JustificationTrace that explains each parameter decision: which source chunk
dominated the outcome, what text from that chunk is the key influence, and
how many other chunks also played a role.

One TraceEntry is produced per parameter (background_color, shape_count, and
all eight fields per shape).

Attribution rules:
  Discrete parameters (color, shape_type, stroke_width): the dominant source
    is the highest-weight voter that voted FOR the winning option.
  Continuous parameters (x, y, size, opacity, shape_count): the dominant
    source is the highest-weight voter overall (they pull the weighted average
    most strongly).

Public API:
  build_trace(artwork_id, voters, params, chunks) → JustificationTrace
  JustificationTrace.to_text()                    → str
"""
import logging
from dataclasses import dataclass

from src.config.settings import COLOR_PALETTE, SHAPE_TYPES, STROKE_WIDTHS
from src.helpers.text_utils import extract_excerpt
from src.models.art_params import ArtParameters
from src.models.corpus import CorpusChunk
from src.models.voting import _hash_choice, _weighted_plurality

logger = logging.getLogger(__name__)

# Option lists — must match voting.py exactly so attribution keys resolve correctly
_COLOR_VALUES:  list[str] = list(COLOR_PALETTE.values())
_STROKE_VALUES: list[int] = sorted(STROKE_WIDTHS.values())


# ── Data model ────────────────────────────────────────────────────────────────

@dataclass
class TraceEntry:
    """Attribution record for a single parameter decision."""
    label:       str   # e.g. "background_color" or "Shape 0 — fill_color"
    value:       str   # resolved parameter value, e.g. "#FF0000" or "circle"
    title:       str   # dominant source's work title
    author:      str   # dominant source's author
    excerpt:     str   # first two sentences from the dominant chunk's text
    other_count: int   # number of other voters (total voters minus the dominant one)


@dataclass
class JustificationTrace:
    """Complete attribution trace for one generated artwork."""
    artwork_id: str
    entries:    list[TraceEntry]

    def to_text(self) -> str:
        """Render the trace as a human-readable plain-text string."""
        lines = [f"artwork_id: {self.artwork_id}", ""]
        for entry in self.entries:
            lines.append(f"{entry.label}: {entry.value}")
            lines.append(f"  {entry.title} ({entry.author})")
            lines.append(f'  "{entry.excerpt}"')
            n = entry.other_count
            lines.append(f"  +{n} chunk{'s' if n != 1 else ''} affected")
            lines.append("")
        return "\n".join(lines).rstrip()


# ── Attribution helpers ───────────────────────────────────────────────────────

def _dominant_discrete(
    voters_normed: list[tuple[str, float]],
    key: str,
    options: list,
) -> str:
    """
    Return the chunk_id of the highest-weight voter that voted for the
    winning option on this discrete parameter.
    """
    winning = _weighted_plurality(
        [(_hash_choice(cid, key, options), w) for cid, w in voters_normed]
    )
    winners = [
        (cid, w)
        for cid, w in voters_normed
        if _hash_choice(cid, key, options) == winning
    ]
    return max(winners, key=lambda x: x[1])[0]


def _dominant_continuous(voters_normed: list[tuple[str, float]]) -> str:
    """Return the chunk_id of the highest-weight voter (pulls average most)."""
    return max(voters_normed, key=lambda x: x[1])[0]


def _entry(
    label: str,
    value: object,
    dominant_id: str,
    total_voter_count: int,
    chunks: dict[str, CorpusChunk],
) -> TraceEntry:
    chunk = chunks.get(dominant_id)
    return TraceEntry(
        label=label,
        value=str(value),
        title=chunk.title  if chunk else "Unknown",
        author=chunk.author if chunk else "Unknown",
        excerpt=extract_excerpt(chunk.text) if chunk else "",
        other_count=total_voter_count - 1,
    )


# ── Public API ────────────────────────────────────────────────────────────────

def build_trace(
    artwork_id: str,
    voters: list[tuple[str, float]],
    params: ArtParameters,
    chunks: dict[str, CorpusChunk],
) -> JustificationTrace:
    """
    Produce a JustificationTrace for the given artwork.

    voters: (chunk_id, weight) — identical to what was passed to vote_on_parameters.
    params: the ArtParameters returned by vote_on_parameters.
    chunks: dict mapping chunk_id → CorpusChunk (for title, author, text lookup).

    Raises ValueError if voters is empty.
    """
    if not voters:
        raise ValueError("voters must not be empty")

    total = sum(w for _, w in voters)
    normed: list[tuple[str, float]] = [(cid, w / total) for cid, w in voters]
    n_voters = len(voters)

    # Continuous dominant is the same voter for every continuous parameter
    top_id = _dominant_continuous(normed)

    entries: list[TraceEntry] = []

    # ── Artwork-level parameters ──────────────────────────────────────────────

    entries.append(_entry(
        "background_color",
        params.background_color,
        _dominant_discrete(normed, "background_color", _COLOR_VALUES),
        n_voters, chunks,
    ))
    entries.append(_entry(
        "shape_count",
        len(params.shapes),
        top_id,
        n_voters, chunks,
    ))

    # ── Per-shape parameters ──────────────────────────────────────────────────

    for i, shape in enumerate(params.shapes):
        p      = f"shape_{i}"
        prefix = f"Shape {i}"

        # Discrete fields — dominant voter is whoever voted for the winning option
        for field, key, options in [
            ("shape_type",   f"{p}_type",         SHAPE_TYPES),
            ("fill_color",   f"{p}_fill",         _COLOR_VALUES),
            ("stroke_color", f"{p}_stroke",       _COLOR_VALUES),
            ("stroke_width", f"{p}_stroke_width", _STROKE_VALUES),
        ]:
            entries.append(_entry(
                f"{prefix} — {field}",
                getattr(shape, field),
                _dominant_discrete(normed, key, options),
                n_voters, chunks,
            ))

        # Continuous fields — dominant voter is the highest-weight voter
        for field in ("x", "y", "size", "opacity"):
            entries.append(_entry(
                f"{prefix} — {field}",
                f"{getattr(shape, field):.4f}",
                top_id,
                n_voters, chunks,
            ))

    logger.debug(
        "build_trace: artwork=%s, %d voters, %d entries",
        artwork_id, n_voters, len(entries),
    )
    return JustificationTrace(artwork_id=artwork_id, entries=entries)
